/**
 * Touchstone 1.1 S-Parameter Parser & Serializer
 * Supports .s2p and .s1p formats
 */
import { SParameterPoint } from '../types/circuit';
import {
  TouchstoneFile,
  TouchstoneHeader,
  TouchstoneFreqUnit,
  TouchstoneFormat,
  TouchstoneParam,
} from '../types/touchstone';

export class TouchstoneEngine {
  /**
   * Export simulation results to standard Touchstone .s2p format
   */
  static exportS2P(
    points: SParameterPoint[],
    circuitName: string = 'CircuitRF_Simulation',
    z0: number = 50,
    format: TouchstoneFormat = 'DB'
  ): string {
    const lines: string[] = [];

    // Header comment lines
    lines.push(`! Touchstone 2-Port S-Parameter Data File`);
    lines.push(`! Generated by CircuitRF Mobile`);
    lines.push(`! Date: ${new Date().toISOString()}`);
    lines.push(`! Circuit: ${circuitName}`);
    lines.push(`! Reference Impedance: ${z0} Ohms`);
    lines.push(`!`);

    // Option line: # <freq unit> <param> <format> R <z0>
    // e.g. # MHz S DB R 50
    lines.push(`# MHz S ${format} R ${z0}`);
    lines.push(`! freq       S11_mag     S11_ang     S21_mag     S21_ang     S12_mag     S12_ang     S22_mag     S22_ang`);

    for (const pt of points) {
      const fStr = pt.freqMHz.toFixed(2).padStart(10, ' ');

      if (format === 'DB') {
        const s11m = pt.s11MagDb.toFixed(3).padStart(11, ' ');
        const s11p = pt.s11PhaseDeg.toFixed(2).padStart(10, ' ');
        const s21m = pt.s21MagDb.toFixed(3).padStart(11, ' ');
        const s21p = pt.s21PhaseDeg.toFixed(2).padStart(10, ' ');
        const s12m = pt.s12MagDb.toFixed(3).padStart(11, ' ');
        const s12p = pt.s12PhaseDeg.toFixed(2).padStart(10, ' ');
        const s22m = pt.s22MagDb.toFixed(3).padStart(11, ' ');
        const s22p = pt.s22PhaseDeg.toFixed(2).padStart(10, ' ');

        lines.push(`${fStr} ${s11m} ${s11p} ${s21m} ${s21p} ${s12m} ${s12p} ${s22m} ${s22p}`);
      } else if (format === 'RI') {
        const s11r = pt.s11Real.toFixed(5).padStart(11, ' ');
        const s11i = pt.s11Imag.toFixed(5).padStart(11, ' ');
        const s21r = pt.s21Real.toFixed(5).padStart(11, ' ');
        const s21i = pt.s21Imag.toFixed(5).padStart(11, ' ');
        const s12r = pt.s12Real.toFixed(5).padStart(11, ' ');
        const s12i = pt.s12Imag.toFixed(5).padStart(11, ' ');
        const s22r = pt.s22Real.toFixed(5).padStart(11, ' ');
        const s22i = pt.s22Imag.toFixed(5).padStart(11, ' ');

        lines.push(`${fStr} ${s11r} ${s11i} ${s21r} ${s21i} ${s12r} ${s12i} ${s22r} ${s22i}`);
      } else {
        // MA
        const s11mag = Math.pow(10, pt.s11MagDb / 20).toFixed(5).padStart(11, ' ');
        const s11p = pt.s11PhaseDeg.toFixed(2).padStart(10, ' ');
        const s21mag = Math.pow(10, pt.s21MagDb / 20).toFixed(5).padStart(11, ' ');
        const s21p = pt.s21PhaseDeg.toFixed(2).padStart(10, ' ');
        const s12mag = Math.pow(10, pt.s12MagDb / 20).toFixed(5).padStart(11, ' ');
        const s12p = pt.s12PhaseDeg.toFixed(2).padStart(10, ' ');
        const s22mag = Math.pow(10, pt.s22MagDb / 20).toFixed(5).padStart(11, ' ');
        const s22p = pt.s22PhaseDeg.toFixed(2).padStart(10, ' ');

        lines.push(`${fStr} ${s11mag} ${s11p} ${s21mag} ${s21p} ${s12mag} ${s12p} ${s22mag} ${s22p}`);
      }
    }

    return lines.join('\n');
  }

  /**
   * Parse Touchstone content (.s2p or .s1p)
   */
  static parse(content: string, filename: string = 'data.s2p'): TouchstoneFile {
    const rawLines = content.split(/\r?\n/);
    const comments: string[] = [];
    let header: TouchstoneHeader = {
      freqUnit: 'MHZ',
      parameterType: 'S',
      format: 'DB',
      referenceResistance: 50.0,
    };

    const rows: TouchstoneFile['rows'] = [];

    for (let line of rawLines) {
      line = line.trim();
      if (!line) continue;

      if (line.startsWith('!')) {
        comments.push(line.slice(1).trim());
        continue;
      }

      if (line.startsWith('#')) {
        // Option line format: # [Hz|kHz|MHz|GHz] [S|Y|Z|G|H] [DB|MA|RI] [R <val>]
        const tokens = line.slice(1).trim().toUpperCase().split(/\s+/);
        let idx = 0;
        while (idx < tokens.length) {
          const t = tokens[idx];
          if (['HZ', 'KHZ', 'MHZ', 'GHZ'].includes(t)) {
            header.freqUnit = t as TouchstoneFreqUnit;
          } else if (['S', 'Y', 'Z', 'G', 'H'].includes(t)) {
            header.parameterType = t as TouchstoneParam;
          } else if (['DB', 'MA', 'RI'].includes(t)) {
            header.format = t as TouchstoneFormat;
          } else if (t === 'R' && idx + 1 < tokens.length) {
            header.referenceResistance = parseFloat(tokens[idx + 1]) || 50.0;
            idx++;
          }
          idx++;
        }
        continue;
      }

      // Data line: tokens are numbers separated by whitespace
      const numTokens = line
        .split(/[,\s]+/)
        .map((s) => parseFloat(s))
        .filter((n) => !isNaN(n));

      if (numTokens.length >= 9) {
        // 2-Port row: freq, s11_1, s11_2, s21_1, s21_2, s12_1, s12_2, s22_1, s22_2
        const freqRaw = numTokens[0];
        let mult = 1e6;
        if (header.freqUnit === 'HZ') mult = 1;
        else if (header.freqUnit === 'KHZ') mult = 1e3;
        else if (header.freqUnit === 'GHZ') mult = 1e9;

        const freqHz = freqRaw * mult;

        rows.push({
          freq: freqRaw,
          freqHz,
          s11: { a: numTokens[1], b: numTokens[2] },
          s21: { a: numTokens[3], b: numTokens[4] },
          s12: { a: numTokens[5], b: numTokens[6] },
          s22: { a: numTokens[7], b: numTokens[8] },
        });
      }
    }

    return {
      filename,
      comments,
      header,
      rows,
    };
  }
}
