/**
 * RF Circuit Presets Library
 */
import { RFPreset } from '../types/circuit';

export const CIRCUIT_PRESETS: RFPreset[] = [
  {
    id: 'lna_2_4ghz',
    name: '2.4 GHz Low Noise Amplifier',
    category: 'Amplifier',
    description: 'High-gain low-noise amplifier for 2.4 GHz ISM / Wi-Fi with input LC match and active HEMT.',
    centerFreqMHz: 2400,
    defaultSweep: {
      startFreqMHz: 1800,
      stopFreqMHz: 3000,
      points: 81,
      z0: 50,
    },
    components: [
      {
        id: 'c_in_dc_block',
        name: 'C_in (DC Block)',
        type: 'capacitor_series',
        value: 12.0,
        unit: 'pF',
        min: 1.0,
        max: 50.0,
        step: 0.5,
        enabled: true,
      },
      {
        id: 'l_in_match',
        name: 'L_in (Input Match)',
        type: 'inductor_series',
        value: 2.8,
        unit: 'nH',
        min: 0.5,
        max: 10.0,
        step: 0.1,
        enabled: true,
      },
      {
        id: 'c_in_shunt',
        name: 'C_in (Shunt Tuning)',
        type: 'capacitor_shunt',
        value: 0.9,
        unit: 'pF',
        min: 0.1,
        max: 5.0,
        step: 0.1,
        enabled: true,
      },
      {
        id: 'hemt_transistor',
        name: 'Q1 (GaAs HEMT)',
        type: 'transistor_active',
        value: 12.0, // transconductance scale
        unit: 'mS',
        min: 2.0,
        max: 25.0,
        step: 1.0,
        secondaryValue: 35.0, // Bias Ids (mA)
        secondaryUnit: 'mA',
        secondaryMin: 10,
        secondaryMax: 80,
        secondaryStep: 5,
        enabled: true,
      },
      {
        id: 'l_out_match',
        name: 'L_out (Output Match)',
        type: 'inductor_series',
        value: 3.3,
        unit: 'nH',
        min: 0.5,
        max: 12.0,
        step: 0.1,
        enabled: true,
      },
      {
        id: 'c_out_dc_block',
        name: 'C_out (DC Block)',
        type: 'capacitor_series',
        value: 15.0,
        unit: 'pF',
        min: 1.0,
        max: 50.0,
        step: 0.5,
        enabled: true,
      },
    ],
  },
  {
    id: 'chebyshev_bpf_1_8ghz',
    name: '1.8 GHz Chebyshev Bandpass Filter',
    category: 'Filter',
    description: '3rd-order lumped-element bandpass filter for cellular 1800 MHz band with steep rejection.',
    centerFreqMHz: 1800,
    defaultSweep: {
      startFreqMHz: 1200,
      stopFreqMHz: 2400,
      points: 81,
      z0: 50,
    },
    components: [
      {
        id: 'c1_series',
        name: 'C1 (Series Resonator)',
        type: 'capacitor_series',
        value: 1.8,
        unit: 'pF',
        min: 0.5,
        max: 8.0,
        step: 0.1,
        enabled: true,
      },
      {
        id: 'l1_series',
        name: 'L1 (Series Resonator)',
        type: 'inductor_series',
        value: 4.3,
        unit: 'nH',
        min: 1.0,
        max: 15.0,
        step: 0.2,
        enabled: true,
      },
      {
        id: 'c2_shunt',
        name: 'C2 (Shunt Tank)',
        type: 'capacitor_shunt',
        value: 3.6,
        unit: 'pF',
        min: 0.5,
        max: 12.0,
        step: 0.2,
        enabled: true,
      },
      {
        id: 'l2_shunt',
        name: 'L2 (Shunt Tank)',
        type: 'inductor_shunt',
        value: 2.1,
        unit: 'nH',
        min: 0.5,
        max: 10.0,
        step: 0.1,
        enabled: true,
      },
      {
        id: 'c3_series',
        name: 'C3 (Series Resonator)',
        type: 'capacitor_series',
        value: 1.8,
        unit: 'pF',
        min: 0.5,
        max: 8.0,
        step: 0.1,
        enabled: true,
      },
      {
        id: 'l3_series',
        name: 'L3 (Series Resonator)',
        type: 'inductor_series',
        value: 4.3,
        unit: 'nH',
        min: 1.0,
        max: 15.0,
        step: 0.2,
        enabled: true,
      },
    ],
  },
  {
    id: 'stepped_lpf_5_8ghz',
    name: '5.8 GHz Stepped-Impedance LPF',
    category: 'Filter',
    description: 'Planar microstrip low-pass filter with alternating high-impedance (inductive) and low-impedance (capacitive) lines.',
    centerFreqMHz: 5800,
    defaultSweep: {
      startFreqMHz: 2000,
      stopFreqMHz: 10000,
      points: 81,
      z0: 50,
    },
    components: [
      {
        id: 'tline_feed1',
        name: 'Feed Line 50Ω',
        type: 'transmission_line',
        value: 50,
        unit: 'Ω',
        min: 30,
        max: 100,
        step: 1,
        secondaryValue: 20, // theta
        secondaryUnit: '°',
        enabled: true,
      },
      {
        id: 'tline_high_z1',
        name: 'High-Z Stub (Inductive)',
        type: 'transmission_line',
        value: 105,
        unit: 'Ω',
        min: 80,
        max: 130,
        step: 1,
        secondaryValue: 42,
        secondaryUnit: '°',
        enabled: true,
      },
      {
        id: 'tline_low_z1',
        name: 'Low-Z Stub (Capacitive)',
        type: 'transmission_line',
        value: 22,
        unit: 'Ω',
        min: 15,
        max: 40,
        step: 1,
        secondaryValue: 65,
        secondaryUnit: '°',
        enabled: true,
      },
      {
        id: 'tline_high_z2',
        name: 'High-Z Stub (Inductive)',
        type: 'transmission_line',
        value: 105,
        unit: 'Ω',
        min: 80,
        max: 130,
        step: 1,
        secondaryValue: 42,
        secondaryUnit: '°',
        enabled: true,
      },
      {
        id: 'tline_feed2',
        name: 'Feed Line 50Ω',
        type: 'transmission_line',
        value: 50,
        unit: 'Ω',
        min: 30,
        max: 100,
        step: 1,
        secondaryValue: 20,
        secondaryUnit: '°',
        enabled: true,
      },
    ],
  },
  {
    id: 'gan_power_amp',
    name: 'GaN Power Amplifier (Loadpull & PAE)',
    category: 'Amplifier',
    description: 'High-power 2.4 GHz GaN HEMT PA configured for Harmonic Balance, 1dB compression, and Loadpull contours.',
    centerFreqMHz: 2400,
    defaultSweep: {
      startFreqMHz: 2000,
      stopFreqMHz: 2800,
      points: 81,
      z0: 50,
    },
    components: [
      {
        id: 'gan_in_tline',
        name: 'Input Matching Line (35Ω)',
        type: 'transmission_line',
        value: 35.0,
        unit: 'Ω',
        min: 20,
        max: 70,
        step: 1,
        secondaryValue: 45,
        secondaryUnit: '°',
        enabled: true,
      },
      {
        id: 'gan_stub',
        name: 'Input Open Stub',
        type: 'open_stub',
        value: 45.0,
        unit: 'Ω',
        min: 25,
        max: 80,
        step: 1,
        secondaryValue: 38,
        secondaryUnit: '°',
        enabled: true,
      },
      {
        id: 'gan_active',
        name: 'GaN HEMT Device',
        type: 'transistor_active',
        value: 18.0, // gm
        unit: 'mS',
        min: 5.0,
        max: 40.0,
        step: 1.0,
        secondaryValue: 80.0, // Ids mA
        secondaryUnit: 'mA',
        secondaryMin: 30,
        secondaryMax: 200,
        secondaryStep: 10,
        enabled: true,
      },
      {
        id: 'gan_out_tline',
        name: 'Output Matching Line (28Ω)',
        type: 'transmission_line',
        value: 28.0,
        unit: 'Ω',
        min: 15,
        max: 60,
        step: 1,
        secondaryValue: 52,
        secondaryUnit: '°',
        enabled: true,
      },
    ],
  },
  {
    id: 'l_match_50_to_complex',
    name: '50Ω to Complex Load Matching Network',
    category: 'Matching',
    description: 'Impedance matching network transforming 50Ω source to 18 + j24 Ω antenna/device load.',
    centerFreqMHz: 1420,
    defaultSweep: {
      startFreqMHz: 1000,
      stopFreqMHz: 2000,
      points: 81,
      z0: 50,
    },
    components: [
      {
        id: 'c_shunt_match',
        name: 'C_shunt (Tuning)',
        type: 'capacitor_shunt',
        value: 3.2,
        unit: 'pF',
        min: 0.5,
        max: 12.0,
        step: 0.1,
        enabled: true,
      },
      {
        id: 'l_series_match',
        name: 'L_series (Matching)',
        type: 'inductor_series',
        value: 4.8,
        unit: 'nH',
        min: 0.5,
        max: 15.0,
        step: 0.2,
        enabled: true,
      },
      {
        id: 'r_load',
        name: 'R_load (Antenna)',
        type: 'resistor_series',
        value: 18.0,
        unit: 'Ω',
        min: 5,
        max: 100,
        step: 1,
        enabled: true,
      },
      {
        id: 'l_load_reactive',
        name: 'L_load (Antenna Reactance)',
        type: 'inductor_series',
        value: 2.7,
        unit: 'nH',
        min: 0.2,
        max: 10.0,
        step: 0.1,
        enabled: true,
      },
    ],
  },
  {
    id: 'wilkinson_divider_3ghz',
    name: '3.0 GHz Wilkinson Power Divider',
    category: 'Passive',
    description: 'Symmetric 2-way power divider with 70.7Ω quarter-wave branches and 100Ω isolation resistor.',
    centerFreqMHz: 3000,
    defaultSweep: {
      startFreqMHz: 1500,
      stopFreqMHz: 4500,
      points: 81,
      z0: 50,
    },
    components: [
      {
        id: 'tline_in',
        name: 'Input 50Ω Feeder',
        type: 'transmission_line',
        value: 50,
        unit: 'Ω',
        min: 40,
        max: 60,
        step: 1,
        secondaryValue: 15,
        secondaryUnit: '°',
        enabled: true,
      },
      {
        id: 'tline_branch',
        name: 'Quarter-Wave Branch (70.7Ω)',
        type: 'transmission_line',
        value: 70.7,
        unit: 'Ω',
        min: 50,
        max: 90,
        step: 0.5,
        secondaryValue: 90,
        secondaryUnit: '°',
        enabled: true,
      },
      {
        id: 'r_isolation',
        name: 'Isolation Resistor (100Ω)',
        type: 'resistor_shunt',
        value: 100.0,
        unit: 'Ω',
        min: 50,
        max: 200,
        step: 5,
        enabled: true,
      },
    ],
  },
  {
    id: 'attenuator_pad_10db',
    name: '10 dB Pi-Attenuator Pad',
    category: 'Passive',
    description: 'Precision 50-ohm 10 dB broadband pi-pad attenuator for RF test benches.',
    centerFreqMHz: 2400,
    defaultSweep: {
      startFreqMHz: 100,
      stopFreqMHz: 6000,
      points: 81,
      z0: 50,
    },
    components: [
      {
        id: 'pad_pi',
        name: '10 dB Pi-Pad',
        type: 'attenuator_pad',
        value: 10.0,
        unit: 'dB',
        min: 1.0,
        max: 30.0,
        step: 0.5,
        secondaryValue: 50.0,
        secondaryUnit: 'Ω',
        enabled: true,
      },
    ],
  },
];
